axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.3
scale_linear_turbo: 0.5

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 1

enable_button: 4  # Left trigger button
enable_turbo_button: 5  # Right trigger button
